"""Remove tag active flag

Revision ID: 81db7767ffae
Revises: 2ae43f1f7374
Create Date: 2025-05-29 13:20:07.375977

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81db7767ffae"
down_revision: Union[str, None] = "2ae43f1f7374"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("active", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
